steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - test_function
      - --region=asia-northeast1
      - --source=.
      - --trigger-http
      - --runtime=python312
      - --no-allow-unauthenticated
options:
  logging: "CLOUD_LOGGING_ONLY"
